Automatically setup conkeror-spawn-helper.

diff --git a/bin/conkeror b/bin/conkeror
--- a/bin/conkeror
+++ b/bin/conkeror
@@ -10,4 +10,15 @@ if [ ! -e ~/src/conkeror ]; then
    echo "Done setting up conkeror"
 fi
 
+if [ ! -e ~/src/conkeror/conkeror-spawn-helper ]; then
+   pushd ~/src/conkeror >/dev/null
+   if ! make; then
+       popd >/dev/null
+       echo "!!! Failed to compile conkeror-spawn-helper"
+       exit 2
+   fi
+   popd >/dev/null
+   echo "Done setting up compiling conkeror-spawn-helper"
+fi
+
 exec ~/src/conkeror/contrib/run-conkeror "$@"
