Whitespace changes to conkeror script.

diff --git a/bin/conkeror b/bin/conkeror
--- a/bin/conkeror
+++ b/bin/conkeror
@@ -1,24 +1,24 @@
 #!/bin/bash
 if [ ! -e ~/src/conkeror ]; then
-   pushd ~/src >/dev/null
-   if ! git clone git://repo.or.cz/conkeror.git; then
-       popd >/dev/null
-       echo "!!! Failed to clone conkeror repo"
-       exit 1
-   fi
-   popd >/dev/null
-   echo "Done setting up conkeror"
+    pushd ~/src >/dev/null
+    if ! git clone git://repo.or.cz/conkeror.git; then
+        popd >/dev/null
+        echo "!!! Failed to clone conkeror repo"
+        exit 1
+    fi
+    popd >/dev/null
+    echo "Done setting up conkeror"
 fi
 
 if [ ! -e ~/src/conkeror/conkeror-spawn-helper ]; then
-   pushd ~/src/conkeror >/dev/null
-   if ! make; then
-       popd >/dev/null
-       echo "!!! Failed to compile conkeror-spawn-helper"
-       exit 2
-   fi
-   popd >/dev/null
-   echo "Done setting up compiling conkeror-spawn-helper"
+    pushd ~/src/conkeror >/dev/null
+    if ! make; then
+        popd >/dev/null
+        echo "!!! Failed to compile conkeror-spawn-helper"
+        exit 2
+    fi
+    popd >/dev/null
+    echo "Done setting up compiling conkeror-spawn-helper"
 fi
 
 exec ~/src/conkeror/contrib/run-conkeror "$@"
