Update leiningen scripts.

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,20 +1,24 @@
 #!/bin/bash
 if [ ! -e ~/src/leiningen ]; then
-   pushd ~/src >/dev/null
-   if ! git clone git@github.com:technomancy/leiningen.git; then
-       popd >/dev/null
-       echo "!!! Failed to clone leiningen repo"
-       exit 1
-   fi
-   popd >/dev/null
-   pushd ~/src/leiningen >/dev/null
-   if ! lein-stable deps; then
-       popd >/dev/null
-       echo "!!! Failed to download leiningen deps"
-       exit 2
-   fi
-   popd >/dev/null
-   echo "Done setting up leiningen"
+    if [ ! -e ~/src ]; then
+	mkdir -p ~/src
+    fi
+    pushd ~/src >/dev/null
+    if ! git clone git@github.com:technomancy/leiningen.git; then
+	popd >/dev/null
+	echo "!!! Failed to clone leiningen repo"
+	exit 1
+    fi
+    popd >/dev/null
+    pushd ~/src/leiningen >/dev/null
+    git checkout 1.x
+    if ! lein-stable deps; then
+	popd >/dev/null
+	echo "!!! Failed to download leiningen deps"
+	exit 2
+    fi
+    popd >/dev/null
+    echo "Done setting up leiningen"
 fi
 
 exec ~/src/leiningen/bin/lein "$@"
